apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: zxcvbnm
  MONGO_INITDB_DATABASE: db_stats
  MYSQL_ROOT_USERNAME: root
  MYSQL_ROOT_PASSWORD: zxcvbnm
  MYSQL_DATABASE: db_grade
