openapi: 3.0.0
info:
  version: 1.0.0
  title: 3495project1
  description: ''
paths:
  /submit_grade:
    post:
      summary: submit a grade
      operationId: app.post_grade
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/submit_grade'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request

components:
  schemas:
    submit_grade:
      type: object
      required:
        - student_id
        - subject
        - grade
        - receive_time
      properties:
        student_id:
          type: string
          example: '1001'
        subject:
          type: string
          example: 'Mathematics'
        grade:
          type: integer
          example: 85
        receive_time:
          type: string
          format: date-time
          example: '2025-01-08T09:12:33.001Z'
        date_recorded:
          type: string
          format: date-time
          example: '2025-01-08T09:12:33.001Z'
